version: "3"
services:
  portal:
    build:
      context: ./
    user: "${U}"
    volumes:
      - ./:/opt
    command:
      bash -c "cd /opt/indigo/ && sh download.sh && cd /opt &&
      make html"
